//! The interfaces `use_cases` needs from the outside world. `infrastructure`
//! implements them; `http::container` picks the implementation.

pub mod activity_log_repository;
pub mod api_token_repository;
pub mod application_repository;
pub mod backup_email_verification_token_repository;
pub mod company_briefing_repository;
pub mod contact_repository;
pub mod conversation_repository;
pub mod cookie_consent_repository;
pub mod document_draft_repository;
pub mod document_repository;
pub mod education_repository;
pub mod email_verification_token_repository;
pub mod interview_round_repository;
pub mod job_posting_source_resolver;
pub mod llm_api_key_repository;
pub mod llm_provider;
pub mod llm_usage_event_repository;
pub mod logger;
pub mod login_event_repository;
pub mod mcp_oauth_authorization_code_repository;
pub mod mcp_oauth_client_repository;
pub mod mcp_oauth_grant_repository;
pub mod mcp_oauth_refresh_token_repository;
pub mod mcp_oauth_token_repository;
pub mod message_repository;
pub mod metrics;
pub mod note_repository;
pub mod notification_repository;
pub mod oauth_account_repository;
pub mod offer_repository;
pub mod outbound_url_policy;
pub mod password_reset_token_repository;
pub mod push_subscription_repository;
pub mod security_event_repository;
pub mod rate_limiter;
pub mod session_blocklist;
pub mod session_repository;
pub mod share_link_repository;
pub mod skill_repository;
pub mod token_service;
pub mod totp_backup_code_repository;
pub mod transaction_manager;
pub mod user_repository;

pub use activity_log_repository::{ActivityLogRepository, AppendActivityLogData};
pub use api_token_repository::{ApiTokenRepository, ApiTokenWithUserEmail, CreateApiTokenData};
pub use application_repository::ApplicationRepository;
pub use backup_email_verification_token_repository::*;
pub use email_verification_token_repository::*;
pub use job_posting_source_resolver::{JobPostingSource, JobPostingSourceResolver};
pub use llm_api_key_repository::{LlmApiKeyRepository, UpsertLlmApiKeyData};
pub use llm_provider::{
    LLMProvider, LlmCompleteOptions, LlmCompleteResult, LlmCompletionResult, LlmMessage, LlmRole,
    LlmStream, LlmStreamChunk, LlmToolCall, LlmToolDefinition, LlmUsage,
};
pub use llm_usage_event_repository::{LlmUsageEventRepository, RecordLlmUsageEventData};
pub use login_event_repository::{CreateLoginEventData, LoginEventRepository};
pub use mcp_oauth_authorization_code_repository::*;
pub use mcp_oauth_client_repository::{CreateMcpOAuthClientData, McpOAuthClientRepository};
pub use mcp_oauth_grant_repository::McpOAuthGrantRepository;
pub use mcp_oauth_refresh_token_repository::*;
pub use mcp_oauth_token_repository::{CreateMcpOAuthAccessTokenData, McpOAuthTokenRepository};
pub use note_repository::{CreateNoteData, NoteRepository};
pub use oauth_account_repository::{CreateOAuthAccountData, OAuthAccountRepository};
pub use password_reset_token_repository::*;
pub use security_event_repository::{CreateSecurityEventData, SecurityEventRepository};
pub use metrics::Metrics;
pub use note_repository::{CreateNoteData, NoteRepository};
pub use rate_limiter::{RateLimit, RateLimiter};
pub use session_blocklist::SessionBlocklist;
pub use session_repository::{CreateSessionData, RotateRefreshTokenData, SessionRepository};
pub use share_link_repository::{CreateShareLinkData, ShareLinkRepository};
pub use token_service::{AccessClaims, RefreshClaims, TokenPair, TokenService};
pub use totp_backup_code_repository::{CreateTotpBackupCodeData, TotpBackupCodeRepository};
pub use user_repository::{CreateUserData, UpdateUserData, UserRepository};
pub mod work_experience_repository;

pub use application_repository::*;
pub use company_briefing_repository::{CompanyBriefingRepository, UpsertCompanyBriefingData};
pub use contact_repository::{ContactRepository, CreateContactData, UpdateContactData};
pub use conversation_repository::{ConversationRepository, CreateConversationData};
pub use cookie_consent_repository::{CookieConsentRepository, CreateCookieConsentData};
pub use document_draft_repository::*;
pub use document_repository::{CreateDocumentData, DocumentRepository};
pub use education_repository::{CreateEducationData, EducationRepository, UpdateEducationData};
pub use interview_round_repository::*;
pub use message_repository::{CreateMessageData, MessageRepository};
pub use notification_repository::*;
pub use offer_repository::{CreateOfferData, OfferRepository, UpdateOfferData};
pub use push_subscription_repository::{PushSubscriptionRepository, UpsertPushSubscriptionData};
pub use skill_repository::{CreateSkillData, SkillRepository, UpdateSkillData};
pub use work_experience_repository::*;
