/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as AccessibilityRouteImport } from './routes/accessibility';
import { Route as AiMcpSetupRouteImport } from './routes/ai-mcp-setup';
import { Route as ConfirmBackupEmailRouteImport } from './routes/confirm-backup-email';
import { Route as ConfirmEmailChangeRouteImport } from './routes/confirm-email-change';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as LoginRouteImport } from './routes/login';
import { Route as PrivacyRouteImport } from './routes/privacy';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as ShareRouteImport } from './routes/share';
import { Route as TermsRouteImport } from './routes/terms';
import { Route as VerifyEmailRouteImport } from './routes/verify-email';
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account';
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics';
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications';
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers';
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route';
import { Route as FeaturesIndexRouteImport } from './routes/features/index';
import { Route as FeaturesAiAssistantRouteImport } from './routes/features/ai-assistant';
import { Route as FeaturesAnalyticsRouteImport } from './routes/features/analytics';
import { Route as FeaturesResumeCoverLetterRouteImport } from './routes/features/resume-cover-letter';
import { Route as FeaturesTrackingRouteImport } from './routes/features/tracking';
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize';
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index';
import { Route as AuthenticatedApplicationsBoardRouteImport } from './routes/_authenticated/applications/board';
import { Route as AuthenticatedApplicationsNewRouteImport } from './routes/_authenticated/applications/new';
import { Route as AuthenticatedApplicationsTrashRouteImport } from './routes/_authenticated/applications/trash';
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant/index';
import { Route as AuthenticatedAssistantHistoryRouteImport } from './routes/_authenticated/assistant/history';
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index';
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai';
import { Route as AuthenticatedSettingsDangerZoneRouteImport } from './routes/_authenticated/settings/danger-zone';
import { Route as AuthenticatedSettingsDataRouteImport } from './routes/_authenticated/settings/data';
import { Route as AuthenticatedSettingsExperienceRouteImport } from './routes/_authenticated/settings/experience';
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations';
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications';
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile';
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security';
import { Route as AuthenticatedApplicationsApplicationIdIndexRouteImport } from './routes/_authenticated/applications/$applicationId/index';
import { Route as AuthenticatedApplicationsApplicationIdEditRouteImport } from './routes/_authenticated/applications/$applicationId/edit';
import { Route as AuthenticatedApplicationsApplicationIdDocumentsDraftIdRouteImport } from './routes/_authenticated/applications/$applicationId/documents/$draftId';
import { Route as AuthenticatedApplicationsApplicationIdDocumentsNewRouteImport } from './routes/_authenticated/applications/$applicationId/documents/new';
import { Route as AuthenticatedApplicationsApplicationIdOffersIndexRouteImport } from './routes/_authenticated/applications/$applicationId/offers/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any);
const AiMcpSetupRoute = AiMcpSetupRouteImport.update({
  id: '/ai-mcp-setup',
  path: '/ai-mcp-setup',
  getParentRoute: () => rootRouteImport,
} as any);
const ConfirmBackupEmailRoute = ConfirmBackupEmailRouteImport.update({
  id: '/confirm-backup-email',
  path: '/confirm-backup-email',
  getParentRoute: () => rootRouteImport,
} as any);
const ConfirmEmailChangeRoute = ConfirmEmailChangeRouteImport.update({
  id: '/confirm-email-change',
  path: '/confirm-email-change',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any);
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any);
const FeaturesAiAssistantRoute = FeaturesAiAssistantRouteImport.update({
  id: '/features/ai-assistant',
  path: '/features/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any);
const FeaturesAnalyticsRoute = FeaturesAnalyticsRouteImport.update({
  id: '/features/analytics',
  path: '/features/analytics',
  getParentRoute: () => rootRouteImport,
} as any);
const FeaturesResumeCoverLetterRoute =
  FeaturesResumeCoverLetterRouteImport.update({
    id: '/features/resume-cover-letter',
    path: '/features/resume-cover-letter',
    getParentRoute: () => rootRouteImport,
  } as any);
const FeaturesTrackingRoute = FeaturesTrackingRouteImport.update({
  id: '/features/tracking',
  path: '/features/tracking',
  getParentRoute: () => rootRouteImport,
} as any);
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedApplicationsBoardRoute =
  AuthenticatedApplicationsBoardRouteImport.update({
    id: '/applications/board',
    path: '/applications/board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedApplicationsNewRoute =
  AuthenticatedApplicationsNewRouteImport.update({
    id: '/applications/new',
    path: '/applications/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedApplicationsTrashRoute =
  AuthenticatedApplicationsTrashRouteImport.update({
    id: '/applications/trash',
    path: '/applications/trash',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/assistant/',
    path: '/assistant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedAssistantHistoryRoute =
  AuthenticatedAssistantHistoryRouteImport.update({
    id: '/assistant/history',
    path: '/assistant/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedSettingsRouteRoute,
} as any);
const AuthenticatedSettingsDangerZoneRoute =
  AuthenticatedSettingsDangerZoneRouteImport.update({
    id: '/danger-zone',
    path: '/danger-zone',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedSettingsDataRoute =
  AuthenticatedSettingsDataRouteImport.update({
    id: '/data',
    path: '/data',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedSettingsExperienceRoute =
  AuthenticatedSettingsExperienceRouteImport.update({
    id: '/experience',
    path: '/experience',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any);
const AuthenticatedApplicationsApplicationIdIndexRoute =
  AuthenticatedApplicationsApplicationIdIndexRouteImport.update({
    id: '/applications/$applicationId/',
    path: '/applications/$applicationId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedApplicationsApplicationIdEditRoute =
  AuthenticatedApplicationsApplicationIdEditRouteImport.update({
    id: '/applications/$applicationId/edit',
    path: '/applications/$applicationId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedApplicationsApplicationIdDocumentsDraftIdRoute =
  AuthenticatedApplicationsApplicationIdDocumentsDraftIdRouteImport.update({
    id: '/applications/$applicationId/documents/$draftId',
    path: '/applications/$applicationId/documents/$draftId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedApplicationsApplicationIdDocumentsNewRoute =
  AuthenticatedApplicationsApplicationIdDocumentsNewRouteImport.update({
    id: '/applications/$applicationId/documents/new',
    path: '/applications/$applicationId/documents/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedApplicationsApplicationIdOffersIndexRoute =
  AuthenticatedApplicationsApplicationIdOffersIndexRouteImport.update({
    id: '/applications/$applicationId/offers/',
    path: '/applications/$applicationId/offers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/accessibility': typeof AccessibilityRoute;
  '/ai-mcp-setup': typeof AiMcpSetupRoute;
  '/confirm-backup-email': typeof ConfirmBackupEmailRoute;
  '/confirm-email-change': typeof ConfirmEmailChangeRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/privacy': typeof PrivacyRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/share': typeof ShareRoute;
  '/terms': typeof TermsRoute;
  '/verify-email': typeof VerifyEmailRoute;
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren;
  '/account': typeof AuthenticatedAccountRoute;
  '/analytics': typeof AuthenticatedAnalyticsRoute;
  '/calendar': typeof AuthenticatedCalendarRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/notifications': typeof AuthenticatedNotificationsRoute;
  '/offers': typeof AuthenticatedOffersRoute;
  '/features/ai-assistant': typeof FeaturesAiAssistantRoute;
  '/features/analytics': typeof FeaturesAnalyticsRoute;
  '/features/resume-cover-letter': typeof FeaturesResumeCoverLetterRoute;
  '/features/tracking': typeof FeaturesTrackingRoute;
  '/oauth/authorize': typeof OauthAuthorizeRoute;
  '/features/': typeof FeaturesIndexRoute;
  '/applications/board': typeof AuthenticatedApplicationsBoardRoute;
  '/applications/new': typeof AuthenticatedApplicationsNewRoute;
  '/applications/trash': typeof AuthenticatedApplicationsTrashRoute;
  '/assistant/history': typeof AuthenticatedAssistantHistoryRoute;
  '/settings/ai': typeof AuthenticatedSettingsAiRoute;
  '/settings/danger-zone': typeof AuthenticatedSettingsDangerZoneRoute;
  '/settings/data': typeof AuthenticatedSettingsDataRoute;
  '/settings/experience': typeof AuthenticatedSettingsExperienceRoute;
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute;
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/applications/': typeof AuthenticatedApplicationsIndexRoute;
  '/assistant/': typeof AuthenticatedAssistantIndexRoute;
  '/settings/': typeof AuthenticatedSettingsIndexRoute;
  '/applications/$applicationId/edit': typeof AuthenticatedApplicationsApplicationIdEditRoute;
  '/applications/$applicationId/': typeof AuthenticatedApplicationsApplicationIdIndexRoute;
  '/applications/$applicationId/documents/$draftId': typeof AuthenticatedApplicationsApplicationIdDocumentsDraftIdRoute;
  '/applications/$applicationId/documents/new': typeof AuthenticatedApplicationsApplicationIdDocumentsNewRoute;
  '/applications/$applicationId/offers/': typeof AuthenticatedApplicationsApplicationIdOffersIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/accessibility': typeof AccessibilityRoute;
  '/ai-mcp-setup': typeof AiMcpSetupRoute;
  '/confirm-backup-email': typeof ConfirmBackupEmailRoute;
  '/confirm-email-change': typeof ConfirmEmailChangeRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/privacy': typeof PrivacyRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/share': typeof ShareRoute;
  '/terms': typeof TermsRoute;
  '/verify-email': typeof VerifyEmailRoute;
  '/account': typeof AuthenticatedAccountRoute;
  '/analytics': typeof AuthenticatedAnalyticsRoute;
  '/calendar': typeof AuthenticatedCalendarRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/notifications': typeof AuthenticatedNotificationsRoute;
  '/offers': typeof AuthenticatedOffersRoute;
  '/features/ai-assistant': typeof FeaturesAiAssistantRoute;
  '/features/analytics': typeof FeaturesAnalyticsRoute;
  '/features/resume-cover-letter': typeof FeaturesResumeCoverLetterRoute;
  '/features/tracking': typeof FeaturesTrackingRoute;
  '/oauth/authorize': typeof OauthAuthorizeRoute;
  '/features': typeof FeaturesIndexRoute;
  '/applications/board': typeof AuthenticatedApplicationsBoardRoute;
  '/applications/new': typeof AuthenticatedApplicationsNewRoute;
  '/applications/trash': typeof AuthenticatedApplicationsTrashRoute;
  '/assistant/history': typeof AuthenticatedAssistantHistoryRoute;
  '/settings/ai': typeof AuthenticatedSettingsAiRoute;
  '/settings/danger-zone': typeof AuthenticatedSettingsDangerZoneRoute;
  '/settings/data': typeof AuthenticatedSettingsDataRoute;
  '/settings/experience': typeof AuthenticatedSettingsExperienceRoute;
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute;
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/applications': typeof AuthenticatedApplicationsIndexRoute;
  '/assistant': typeof AuthenticatedAssistantIndexRoute;
  '/settings': typeof AuthenticatedSettingsIndexRoute;
  '/applications/$applicationId/edit': typeof AuthenticatedApplicationsApplicationIdEditRoute;
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdIndexRoute;
  '/applications/$applicationId/documents/$draftId': typeof AuthenticatedApplicationsApplicationIdDocumentsDraftIdRoute;
  '/applications/$applicationId/documents/new': typeof AuthenticatedApplicationsApplicationIdDocumentsNewRoute;
  '/applications/$applicationId/offers': typeof AuthenticatedApplicationsApplicationIdOffersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren;
  '/accessibility': typeof AccessibilityRoute;
  '/ai-mcp-setup': typeof AiMcpSetupRoute;
  '/confirm-backup-email': typeof ConfirmBackupEmailRoute;
  '/confirm-email-change': typeof ConfirmEmailChangeRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/privacy': typeof PrivacyRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/share': typeof ShareRoute;
  '/terms': typeof TermsRoute;
  '/verify-email': typeof VerifyEmailRoute;
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren;
  '/_authenticated/account': typeof AuthenticatedAccountRoute;
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute;
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute;
  '/_authenticated/offers': typeof AuthenticatedOffersRoute;
  '/features/ai-assistant': typeof FeaturesAiAssistantRoute;
  '/features/analytics': typeof FeaturesAnalyticsRoute;
  '/features/resume-cover-letter': typeof FeaturesResumeCoverLetterRoute;
  '/features/tracking': typeof FeaturesTrackingRoute;
  '/oauth/authorize': typeof OauthAuthorizeRoute;
  '/features/': typeof FeaturesIndexRoute;
  '/_authenticated/applications/board': typeof AuthenticatedApplicationsBoardRoute;
  '/_authenticated/applications/new': typeof AuthenticatedApplicationsNewRoute;
  '/_authenticated/applications/trash': typeof AuthenticatedApplicationsTrashRoute;
  '/_authenticated/assistant/history': typeof AuthenticatedAssistantHistoryRoute;
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute;
  '/_authenticated/settings/danger-zone': typeof AuthenticatedSettingsDangerZoneRoute;
  '/_authenticated/settings/data': typeof AuthenticatedSettingsDataRoute;
  '/_authenticated/settings/experience': typeof AuthenticatedSettingsExperienceRoute;
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute;
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute;
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute;
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute;
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute;
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute;
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute;
  '/_authenticated/applications/$applicationId/edit': typeof AuthenticatedApplicationsApplicationIdEditRoute;
  '/_authenticated/applications/$applicationId/': typeof AuthenticatedApplicationsApplicationIdIndexRoute;
  '/_authenticated/applications/$applicationId/documents/$draftId': typeof AuthenticatedApplicationsApplicationIdDocumentsDraftIdRoute;
  '/_authenticated/applications/$applicationId/documents/new': typeof AuthenticatedApplicationsApplicationIdDocumentsNewRoute;
  '/_authenticated/applications/$applicationId/offers/': typeof AuthenticatedApplicationsApplicationIdOffersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/accessibility'
    | '/ai-mcp-setup'
    | '/confirm-backup-email'
    | '/confirm-email-change'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/share'
    | '/terms'
    | '/verify-email'
    | '/settings'
    | '/account'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/notifications'
    | '/offers'
    | '/features/ai-assistant'
    | '/features/analytics'
    | '/features/resume-cover-letter'
    | '/features/tracking'
    | '/oauth/authorize'
    | '/features/'
    | '/applications/board'
    | '/applications/new'
    | '/applications/trash'
    | '/assistant/history'
    | '/settings/ai'
    | '/settings/danger-zone'
    | '/settings/data'
    | '/settings/experience'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/applications/'
    | '/assistant/'
    | '/settings/'
    | '/applications/$applicationId/edit'
    | '/applications/$applicationId/'
    | '/applications/$applicationId/documents/$draftId'
    | '/applications/$applicationId/documents/new'
    | '/applications/$applicationId/offers/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/accessibility'
    | '/ai-mcp-setup'
    | '/confirm-backup-email'
    | '/confirm-email-change'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/share'
    | '/terms'
    | '/verify-email'
    | '/account'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/notifications'
    | '/offers'
    | '/features/ai-assistant'
    | '/features/analytics'
    | '/features/resume-cover-letter'
    | '/features/tracking'
    | '/oauth/authorize'
    | '/features'
    | '/applications/board'
    | '/applications/new'
    | '/applications/trash'
    | '/assistant/history'
    | '/settings/ai'
    | '/settings/danger-zone'
    | '/settings/data'
    | '/settings/experience'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/applications'
    | '/assistant'
    | '/settings'
    | '/applications/$applicationId/edit'
    | '/applications/$applicationId'
    | '/applications/$applicationId/documents/$draftId'
    | '/applications/$applicationId/documents/new'
    | '/applications/$applicationId/offers';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accessibility'
    | '/ai-mcp-setup'
    | '/confirm-backup-email'
    | '/confirm-email-change'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/share'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/settings'
    | '/_authenticated/account'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/offers'
    | '/features/ai-assistant'
    | '/features/analytics'
    | '/features/resume-cover-letter'
    | '/features/tracking'
    | '/oauth/authorize'
    | '/features/'
    | '/_authenticated/applications/board'
    | '/_authenticated/applications/new'
    | '/_authenticated/applications/trash'
    | '/_authenticated/assistant/history'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/danger-zone'
    | '/_authenticated/settings/data'
    | '/_authenticated/settings/experience'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/applications/'
    | '/_authenticated/assistant/'
    | '/_authenticated/settings/'
    | '/_authenticated/applications/$applicationId/edit'
    | '/_authenticated/applications/$applicationId/'
    | '/_authenticated/applications/$applicationId/documents/$draftId'
    | '/_authenticated/applications/$applicationId/documents/new'
    | '/_authenticated/applications/$applicationId/offers/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  AccessibilityRoute: typeof AccessibilityRoute;
  AiMcpSetupRoute: typeof AiMcpSetupRoute;
  ConfirmBackupEmailRoute: typeof ConfirmBackupEmailRoute;
  ConfirmEmailChangeRoute: typeof ConfirmEmailChangeRoute;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  PrivacyRoute: typeof PrivacyRoute;
  RegisterRoute: typeof RegisterRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  ShareRoute: typeof ShareRoute;
  TermsRoute: typeof TermsRoute;
  VerifyEmailRoute: typeof VerifyEmailRoute;
  FeaturesAiAssistantRoute: typeof FeaturesAiAssistantRoute;
  FeaturesAnalyticsRoute: typeof FeaturesAnalyticsRoute;
  FeaturesResumeCoverLetterRoute: typeof FeaturesResumeCoverLetterRoute;
  FeaturesTrackingRoute: typeof FeaturesTrackingRoute;
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute;
  FeaturesIndexRoute: typeof FeaturesIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/accessibility': {
      id: '/accessibility';
      path: '/accessibility';
      fullPath: '/accessibility';
      preLoaderRoute: typeof AccessibilityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/ai-mcp-setup': {
      id: '/ai-mcp-setup';
      path: '/ai-mcp-setup';
      fullPath: '/ai-mcp-setup';
      preLoaderRoute: typeof AiMcpSetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/confirm-backup-email': {
      id: '/confirm-backup-email';
      path: '/confirm-backup-email';
      fullPath: '/confirm-backup-email';
      preLoaderRoute: typeof ConfirmBackupEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/confirm-email-change': {
      id: '/confirm-email-change';
      path: '/confirm-email-change';
      fullPath: '/confirm-email-change';
      preLoaderRoute: typeof ConfirmEmailChangeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/privacy': {
      id: '/privacy';
      path: '/privacy';
      fullPath: '/privacy';
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/share': {
      id: '/share';
      path: '/share';
      fullPath: '/share';
      preLoaderRoute: typeof ShareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/terms': {
      id: '/terms';
      path: '/terms';
      fullPath: '/terms';
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/verify-email': {
      id: '/verify-email';
      path: '/verify-email';
      fullPath: '/verify-email';
      preLoaderRoute: typeof VerifyEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/account': {
      id: '/_authenticated/account';
      path: '/account';
      fullPath: '/account';
      preLoaderRoute: typeof AuthenticatedAccountRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics';
      path: '/analytics';
      fullPath: '/analytics';
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar';
      path: '/calendar';
      fullPath: '/calendar';
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications';
      path: '/notifications';
      fullPath: '/notifications';
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/offers': {
      id: '/_authenticated/offers';
      path: '/offers';
      fullPath: '/offers';
      preLoaderRoute: typeof AuthenticatedOffersRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/settings': {
      id: '/_authenticated/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/features/': {
      id: '/features/';
      path: '/features';
      fullPath: '/features/';
      preLoaderRoute: typeof FeaturesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/features/ai-assistant': {
      id: '/features/ai-assistant';
      path: '/features/ai-assistant';
      fullPath: '/features/ai-assistant';
      preLoaderRoute: typeof FeaturesAiAssistantRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/features/analytics': {
      id: '/features/analytics';
      path: '/features/analytics';
      fullPath: '/features/analytics';
      preLoaderRoute: typeof FeaturesAnalyticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/features/resume-cover-letter': {
      id: '/features/resume-cover-letter';
      path: '/features/resume-cover-letter';
      fullPath: '/features/resume-cover-letter';
      preLoaderRoute: typeof FeaturesResumeCoverLetterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/features/tracking': {
      id: '/features/tracking';
      path: '/features/tracking';
      fullPath: '/features/tracking';
      preLoaderRoute: typeof FeaturesTrackingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/oauth/authorize': {
      id: '/oauth/authorize';
      path: '/oauth/authorize';
      fullPath: '/oauth/authorize';
      preLoaderRoute: typeof OauthAuthorizeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/';
      path: '/applications';
      fullPath: '/applications/';
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/applications/board': {
      id: '/_authenticated/applications/board';
      path: '/applications/board';
      fullPath: '/applications/board';
      preLoaderRoute: typeof AuthenticatedApplicationsBoardRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/applications/new': {
      id: '/_authenticated/applications/new';
      path: '/applications/new';
      fullPath: '/applications/new';
      preLoaderRoute: typeof AuthenticatedApplicationsNewRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/applications/trash': {
      id: '/_authenticated/applications/trash';
      path: '/applications/trash';
      fullPath: '/applications/trash';
      preLoaderRoute: typeof AuthenticatedApplicationsTrashRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/';
      path: '/assistant';
      fullPath: '/assistant/';
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/assistant/history': {
      id: '/_authenticated/assistant/history';
      path: '/assistant/history';
      fullPath: '/assistant/history';
      preLoaderRoute: typeof AuthenticatedAssistantHistoryRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/';
      path: '/';
      fullPath: '/settings/';
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai';
      path: '/ai';
      fullPath: '/settings/ai';
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/danger-zone': {
      id: '/_authenticated/settings/danger-zone';
      path: '/danger-zone';
      fullPath: '/settings/danger-zone';
      preLoaderRoute: typeof AuthenticatedSettingsDangerZoneRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/data': {
      id: '/_authenticated/settings/data';
      path: '/data';
      fullPath: '/settings/data';
      preLoaderRoute: typeof AuthenticatedSettingsDataRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/experience': {
      id: '/_authenticated/settings/experience';
      path: '/experience';
      fullPath: '/settings/experience';
      preLoaderRoute: typeof AuthenticatedSettingsExperienceRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations';
      path: '/integrations';
      fullPath: '/settings/integrations';
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications';
      path: '/notifications';
      fullPath: '/settings/notifications';
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile';
      path: '/profile';
      fullPath: '/settings/profile';
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security';
      path: '/security';
      fullPath: '/settings/security';
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport;
      parentRoute: typeof AuthenticatedSettingsRouteRoute;
    };
    '/_authenticated/applications/$applicationId/': {
      id: '/_authenticated/applications/$applicationId/';
      path: '/applications/$applicationId';
      fullPath: '/applications/$applicationId/';
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/applications/$applicationId/edit': {
      id: '/_authenticated/applications/$applicationId/edit';
      path: '/applications/$applicationId/edit';
      fullPath: '/applications/$applicationId/edit';
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdEditRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/applications/$applicationId/documents/$draftId': {
      id: '/_authenticated/applications/$applicationId/documents/$draftId';
      path: '/applications/$applicationId/documents/$draftId';
      fullPath: '/applications/$applicationId/documents/$draftId';
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdDocumentsDraftIdRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/applications/$applicationId/documents/new': {
      id: '/_authenticated/applications/$applicationId/documents/new';
      path: '/applications/$applicationId/documents/new';
      fullPath: '/applications/$applicationId/documents/new';
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdDocumentsNewRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/applications/$applicationId/offers/': {
      id: '/_authenticated/applications/$applicationId/offers/';
      path: '/applications/$applicationId/offers';
      fullPath: '/applications/$applicationId/offers/';
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdOffersIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute;
  AuthenticatedSettingsDangerZoneRoute: typeof AuthenticatedSettingsDangerZoneRoute;
  AuthenticatedSettingsDataRoute: typeof AuthenticatedSettingsDataRoute;
  AuthenticatedSettingsExperienceRoute: typeof AuthenticatedSettingsExperienceRoute;
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute;
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute;
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute;
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute;
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute;
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
    AuthenticatedSettingsDangerZoneRoute: AuthenticatedSettingsDangerZoneRoute,
    AuthenticatedSettingsDataRoute: AuthenticatedSettingsDataRoute,
    AuthenticatedSettingsExperienceRoute: AuthenticatedSettingsExperienceRoute,
    AuthenticatedSettingsIntegrationsRoute:
      AuthenticatedSettingsIntegrationsRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
    AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  };

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  );

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren;
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute;
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute;
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute;
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute;
  AuthenticatedApplicationsBoardRoute: typeof AuthenticatedApplicationsBoardRoute;
  AuthenticatedApplicationsNewRoute: typeof AuthenticatedApplicationsNewRoute;
  AuthenticatedApplicationsTrashRoute: typeof AuthenticatedApplicationsTrashRoute;
  AuthenticatedAssistantHistoryRoute: typeof AuthenticatedAssistantHistoryRoute;
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute;
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute;
  AuthenticatedApplicationsApplicationIdEditRoute: typeof AuthenticatedApplicationsApplicationIdEditRoute;
  AuthenticatedApplicationsApplicationIdIndexRoute: typeof AuthenticatedApplicationsApplicationIdIndexRoute;
  AuthenticatedApplicationsApplicationIdDocumentsDraftIdRoute: typeof AuthenticatedApplicationsApplicationIdDocumentsDraftIdRoute;
  AuthenticatedApplicationsApplicationIdDocumentsNewRoute: typeof AuthenticatedApplicationsApplicationIdDocumentsNewRoute;
  AuthenticatedApplicationsApplicationIdOffersIndexRoute: typeof AuthenticatedApplicationsApplicationIdOffersIndexRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedApplicationsBoardRoute: AuthenticatedApplicationsBoardRoute,
  AuthenticatedApplicationsNewRoute: AuthenticatedApplicationsNewRoute,
  AuthenticatedApplicationsTrashRoute: AuthenticatedApplicationsTrashRoute,
  AuthenticatedAssistantHistoryRoute: AuthenticatedAssistantHistoryRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  AuthenticatedApplicationsApplicationIdEditRoute:
    AuthenticatedApplicationsApplicationIdEditRoute,
  AuthenticatedApplicationsApplicationIdIndexRoute:
    AuthenticatedApplicationsApplicationIdIndexRoute,
  AuthenticatedApplicationsApplicationIdDocumentsDraftIdRoute:
    AuthenticatedApplicationsApplicationIdDocumentsDraftIdRoute,
  AuthenticatedApplicationsApplicationIdDocumentsNewRoute:
    AuthenticatedApplicationsApplicationIdDocumentsNewRoute,
  AuthenticatedApplicationsApplicationIdOffersIndexRoute:
    AuthenticatedApplicationsApplicationIdOffersIndexRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AiMcpSetupRoute: AiMcpSetupRoute,
  ConfirmBackupEmailRoute: ConfirmBackupEmailRoute,
  ConfirmEmailChangeRoute: ConfirmEmailChangeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShareRoute: ShareRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  FeaturesAiAssistantRoute: FeaturesAiAssistantRoute,
  FeaturesAnalyticsRoute: FeaturesAnalyticsRoute,
  FeaturesResumeCoverLetterRoute: FeaturesResumeCoverLetterRoute,
  FeaturesTrackingRoute: FeaturesTrackingRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
