import type { RestoreApplicationUseCase } from '#src/use-cases/jobs/RestoreApplicationUseCase.js';
import type { PermanentlyDeleteApplicationUseCase } from '#src/use-cases/jobs/PermanentlyDeleteApplicationUseCase.js';
import type { ListTrashedApplicationsUseCase } from '#src/use-cases/jobs/ListTrashedApplicationsUseCase.js';
import type { PurgeExpiredApplicationsUseCase } from '#src/use-cases/jobs/PurgeExpiredApplicationsUseCase.js';
import type { db } from '#src/infrastructure/db/client.js';

import type { ICache } from '#src/infrastructure/cache/ICache.js';
import type { DrizzleUserRepository } from '#src/infrastructure/db/repositories/DrizzleUserRepository.js';
import type { DrizzleApplicationRepository } from '#src/infrastructure/db/repositories/DrizzleApplicationRepository.js';
import type { DrizzleNoteRepository } from '#src/infrastructure/db/repositories/DrizzleNoteRepository.js';
import type { DrizzleDocumentRepository } from '#src/infrastructure/db/repositories/DrizzleDocumentRepository.js';
import type { DrizzleDocumentDraftRepository } from '#src/infrastructure/db/repositories/DrizzleDocumentDraftRepository.js';
import type { CachedApplicationRepository } from '#src/infrastructure/db/repositories/CachedApplicationRepository.js';
import type { CachedNoteRepository } from '#src/infrastructure/db/repositories/CachedNoteRepository.js';
import type { CachedApiTokenRepository } from '#src/infrastructure/db/repositories/CachedApiTokenRepository.js';
import type { CachedContactRepository } from '#src/infrastructure/db/repositories/CachedContactRepository.js';
import type { CachedNotificationRepository } from '#src/infrastructure/db/repositories/CachedNotificationRepository.js';
import type { CachedDocumentRepository } from '#src/infrastructure/db/repositories/CachedDocumentRepository.js';
import type { DrizzleInterviewRoundRepository } from '#src/infrastructure/db/repositories/DrizzleInterviewRoundRepository.js';
import type { CachedInterviewRoundRepository } from '#src/infrastructure/db/repositories/CachedInterviewRoundRepository.js';
import type { CachedUserRepository } from '#src/infrastructure/db/repositories/CachedUserRepository.js';
import type { CachedSkillRepository } from '#src/infrastructure/db/repositories/CachedSkillRepository.js';
import type { CachedEducationRepository } from '#src/infrastructure/db/repositories/CachedEducationRepository.js';
import type { CachedWorkExperienceRepository } from '#src/infrastructure/db/repositories/CachedWorkExperienceRepository.js';
import type { DrizzleActivityLogRepository } from '#src/infrastructure/db/repositories/DrizzleActivityLogRepository.js';
import type { DrizzlePushSubscriptionRepository } from '#src/infrastructure/db/repositories/DrizzlePushSubscriptionRepository.js';
import type { DrizzleContactRepository } from '#src/infrastructure/db/repositories/DrizzleContactRepository.js';
import type { DrizzlePasswordResetTokenRepository } from '#src/infrastructure/db/repositories/DrizzlePasswordResetTokenRepository.js';
import type { DrizzleLoginEventRepository } from '#src/infrastructure/db/repositories/DrizzleLoginEventRepository.js';
import type { DrizzleSecurityEventRepository } from '#src/infrastructure/db/repositories/DrizzleSecurityEventRepository.js';
import type { DrizzleCookieConsentRepository } from '#src/infrastructure/db/repositories/DrizzleCookieConsentRepository.js';
import type { DrizzleSessionRepository } from '#src/infrastructure/db/repositories/DrizzleSessionRepository.js';
import type { BlocklistingSessionRepository } from '#src/infrastructure/db/repositories/BlocklistingSessionRepository.js';
import type { ISessionBlocklist } from '#src/use-cases/ports/ISessionBlocklist.js';
import type { DrizzleWorkExperienceRepository } from '#src/infrastructure/db/repositories/DrizzleWorkExperienceRepository.js';
import type { DrizzleEducationRepository } from '#src/infrastructure/db/repositories/DrizzleEducationRepository.js';
import type { DrizzleSkillRepository } from '#src/infrastructure/db/repositories/DrizzleSkillRepository.js';
import type { DrizzleMessageRepository } from '#src/infrastructure/db/repositories/DrizzleMessageRepository.js';
import type { DrizzleConversationRepository } from '#src/infrastructure/db/repositories/DrizzleConversationRepository.js';
import type { DrizzleEmailVerificationTokenRepository } from '#src/infrastructure/db/repositories/DrizzleEmailVerificationTokenRepository.js';
import type { DrizzleTotpBackupCodeRepository } from '#src/infrastructure/db/repositories/DrizzleTotpBackupCodeRepository.js';
import type { DrizzleBackupEmailVerificationTokenRepository } from '#src/infrastructure/db/repositories/DrizzleBackupEmailVerificationTokenRepository.js';
import type { DrizzleOAuthAccountRepository } from '#src/infrastructure/db/repositories/DrizzleOAuthAccountRepository.js';
import type { DrizzleApiTokenRepository } from '#src/infrastructure/db/repositories/DrizzleApiTokenRepository.js';
import type { DrizzleMcpOAuthTokenRepository } from '#src/infrastructure/db/repositories/DrizzleMcpOAuthTokenRepository.js';
import type { CachedMcpOAuthTokenRepository } from '#src/infrastructure/db/repositories/CachedMcpOAuthTokenRepository.js';
import type { DrizzleMcpOAuthClientRepository } from '#src/infrastructure/db/repositories/DrizzleMcpOAuthClientRepository.js';
import type { DrizzleMcpOAuthAuthorizationCodeRepository } from '#src/infrastructure/db/repositories/DrizzleMcpOAuthAuthorizationCodeRepository.js';
import type { DrizzleShareLinkRepository } from '#src/infrastructure/db/repositories/DrizzleShareLinkRepository.js';
import type { DrizzleNotificationRepository } from '#src/infrastructure/db/repositories/DrizzleNotificationRepository.js';
import type { DrizzleOfferRepository } from '#src/infrastructure/db/repositories/DrizzleOfferRepository.js';
import type { IRateLimiter } from '#src/use-cases/ports/IRateLimiter.js';
import type { ITotpProvider } from '#src/use-cases/ports/ITotpProvider.js';
import type { OAuthProviderRegistry } from '#src/infrastructure/auth/OAuthProviderRegistry.js';
import type { McpOAuthConsentService } from '#src/infrastructure/auth/McpOAuthConsentService.js';
import type { OAuthStateService } from '#src/infrastructure/auth/OAuthStateService.js';
import type { MobileOAuthHandoffService } from '#src/infrastructure/auth/MobileOAuthHandoffService.js';
import type { IOAuthProvider } from '#src/use-cases/ports/IOAuthProvider.js';
import type { LoginOrSignupWithOAuthUseCase } from '#src/use-cases/oauth/LoginOrSignupWithOAuthUseCase.js';
import type { LinkOAuthAccountUseCase } from '#src/use-cases/oauth/LinkOAuthAccountUseCase.js';
import type { UnlinkOAuthAccountUseCase } from '#src/use-cases/oauth/UnlinkOAuthAccountUseCase.js';
import type { ListLinkedOAuthAccountsUseCase } from '#src/use-cases/oauth/ListLinkedOAuthAccountsUseCase.js';
import type { ExchangeMobileOAuthCodeUseCase } from '#src/use-cases/oauth/ExchangeMobileOAuthCodeUseCase.js';
import type { OAuthAccountMapper } from '#src/interface-adapters/mappers/OAuthAccountMapper.js';
import type { OAuthResolver } from '#src/interface-adapters/resolvers/OAuthResolver.js';
import type { WorkExperienceResolver } from '#src/interface-adapters/resolvers/WorkExperienceResolver.js';
import type { EducationResolver } from '#src/interface-adapters/resolvers/EducationResolver.js';
import type { SkillResolver } from '#src/interface-adapters/resolvers/SkillResolver.js';

import type { LocalStorageProvider } from '#src/infrastructure/storage/LocalStorageProvider.js';
import type { VercelBlobStorageProvider } from '#src/infrastructure/storage/VercelBlobStorageProvider.js';

import type { ApplicationMapper } from '#src/interface-adapters/mappers/ApplicationMapper.js';
import type { NoteMapper } from '#src/interface-adapters/mappers/NoteMapper.js';
import type { DocumentMapper } from '#src/interface-adapters/mappers/DocumentMapper.js';
import type { DocumentDraftMapper } from '#src/interface-adapters/mappers/DocumentDraftMapper.js';
import type { UserMapper } from '#src/interface-adapters/mappers/UserMapper.js';
import type { InterviewRoundMapper } from '#src/interface-adapters/mappers/InterviewRoundMapper.js';
import type { ActivityLogMapper } from '#src/interface-adapters/mappers/ActivityLogMapper.js';
import type { ContactMapper } from '#src/interface-adapters/mappers/ContactMapper.js';
import type { LoginEventMapper } from '#src/interface-adapters/mappers/LoginEventMapper.js';
import type { SecurityActivityMapper } from '#src/interface-adapters/mappers/SecurityActivityMapper.js';
import type { MessageMapper } from '#src/interface-adapters/mappers/MessageMapper.js';
import type { ConversationMapper } from '#src/interface-adapters/mappers/ConversationMapper.js';
import type { SessionMapper } from '#src/interface-adapters/mappers/SessionMapper.js';
import type { WorkExperienceMapper } from '#src/interface-adapters/mappers/WorkExperienceMapper.js';
import type { EducationMapper } from '#src/interface-adapters/mappers/EducationMapper.js';
import type { SkillMapper } from '#src/interface-adapters/mappers/SkillMapper.js';

import type { AuthResolver } from '#src/interface-adapters/resolvers/AuthResolver.js';
import type { ApplicationResolver } from '#src/interface-adapters/resolvers/ApplicationResolver.js';
import type { NoteResolver } from '#src/interface-adapters/resolvers/NoteResolver.js';
import type { DocumentResolver } from '#src/interface-adapters/resolvers/DocumentResolver.js';
import type { DocumentDraftResolver } from '#src/interface-adapters/resolvers/DocumentDraftResolver.js';
import type { UserResolver } from '#src/interface-adapters/resolvers/UserResolver.js';
import type { InterviewRoundResolver } from '#src/interface-adapters/resolvers/InterviewRoundResolver.js';
import type { ActivityLogResolver } from '#src/interface-adapters/resolvers/ActivityLogResolver.js';
import type { ContactResolver } from '#src/interface-adapters/resolvers/ContactResolver.js';
import type { LoginEventResolver } from '#src/interface-adapters/resolvers/LoginEventResolver.js';
import type { SecurityActivityResolver } from '#src/interface-adapters/resolvers/SecurityActivityResolver.js';
import type { ApiTokenResolver } from '#src/interface-adapters/resolvers/ApiTokenResolver.js';
import type { McpOAuthGrantResolver } from '#src/interface-adapters/resolvers/McpOAuthGrantResolver.js';
import type { NotificationResolver } from '#src/interface-adapters/resolvers/NotificationResolver.js';
import type { CookieConsentResolver } from '#src/interface-adapters/resolvers/CookieConsentResolver.js';
import type { SessionResolver } from '#src/interface-adapters/resolvers/SessionResolver.js';
import type { McpController } from '#src/interface-adapters/mcp/McpController.js';

import type { AuthenticateRequestUseCase } from '#src/use-cases/auth/AuthenticateRequestUseCase.js';
import type { AuthenticateMcpRequestUseCase } from '#src/use-cases/auth/AuthenticateMcpRequestUseCase.js';
import type { ValidateMcpOAuthAccessTokenUseCase } from '#src/use-cases/mcpOAuth/ValidateMcpOAuthAccessTokenUseCase.js';
import type { CreateMcpOAuthAccessTokenUseCase } from '#src/use-cases/mcpOAuth/CreateMcpOAuthAccessTokenUseCase.js';
import type { RegisterMcpOAuthClientUseCase } from '#src/use-cases/mcpOAuth/RegisterMcpOAuthClientUseCase.js';
import type { CreateMcpOAuthAuthorizationCodeUseCase } from '#src/use-cases/mcpOAuth/CreateMcpOAuthAuthorizationCodeUseCase.js';
import type { ExchangeMcpOAuthAuthorizationCodeUseCase } from '#src/use-cases/mcpOAuth/ExchangeMcpOAuthAuthorizationCodeUseCase.js';
import type { RevokeMcpOAuthGrantUseCase } from '#src/use-cases/mcpOAuth/RevokeMcpOAuthGrantUseCase.js';
import type { DrizzleMcpOAuthRefreshTokenRepository } from '#src/infrastructure/db/repositories/DrizzleMcpOAuthRefreshTokenRepository.js';
import type { DrizzleMcpOAuthGrantRepository } from '#src/infrastructure/db/repositories/DrizzleMcpOAuthGrantRepository.js';
import type { CreateMcpOAuthRefreshTokenUseCase } from '#src/use-cases/mcpOAuth/CreateMcpOAuthRefreshTokenUseCase.js';
import type { RotateMcpOAuthRefreshTokenUseCase } from '#src/use-cases/mcpOAuth/RotateMcpOAuthRefreshTokenUseCase.js';
import type { ListMcpOAuthGrantsUseCase } from '#src/use-cases/mcpOAuth/ListMcpOAuthGrantsUseCase.js';
import type { RevokeMcpOAuthGrantForUserUseCase } from '#src/use-cases/mcpOAuth/RevokeMcpOAuthGrantForUserUseCase.js';
import type { RegisterUseCase } from '#src/use-cases/auth/RegisterUseCase.js';
import type { LoginUseCase } from '#src/use-cases/auth/LoginUseCase.js';
import type { LoginWithTotpUseCase } from '#src/use-cases/auth/LoginWithTotpUseCase.js';
import type { ReauthenticateUseCase } from '#src/use-cases/auth/ReauthenticateUseCase.js';
import type { RequestPasswordResetUseCase } from '#src/use-cases/auth/RequestPasswordResetUseCase.js';
import type { ResetPasswordUseCase } from '#src/use-cases/auth/ResetPasswordUseCase.js';
import type { SendEmailVerificationUseCase } from '#src/use-cases/auth/SendEmailVerificationUseCase.js';
import type { VerifyEmailUseCase } from '#src/use-cases/auth/VerifyEmailUseCase.js';
import type { CreateApplicationUseCase } from '#src/use-cases/jobs/CreateApplicationUseCase.js';
import type { GetApplicationsUseCase } from '#src/use-cases/jobs/GetApplicationsUseCase.js';
import type { GetApplicationsPageUseCase } from '#src/use-cases/jobs/GetApplicationsPageUseCase.js';
import type { GetApplicationUseCase } from '#src/use-cases/jobs/GetApplicationUseCase.js';
import type { UpdateApplicationUseCase } from '#src/use-cases/jobs/UpdateApplicationUseCase.js';
import type { MoveApplicationOnBoardUseCase } from '#src/use-cases/jobs/MoveApplicationOnBoardUseCase.js';
import type { DeleteApplicationUseCase } from '#src/use-cases/jobs/DeleteApplicationUseCase.js';
import type { BulkUpdateApplicationsUseCase } from '#src/use-cases/jobs/BulkUpdateApplicationsUseCase.js';
import type { BulkDeleteApplicationsUseCase } from '#src/use-cases/jobs/BulkDeleteApplicationsUseCase.js';
import type { BulkRestoreApplicationsUseCase } from '#src/use-cases/jobs/BulkRestoreApplicationsUseCase.js';
import type { EmptyTrashUseCase } from '#src/use-cases/jobs/EmptyTrashUseCase.js';
import type { GetApplicationSectionCountsUseCase } from '#src/use-cases/jobs/GetApplicationSectionCountsUseCase.js';
import type { BulkAddTagToApplicationsUseCase } from '#src/use-cases/jobs/BulkAddTagToApplicationsUseCase.js';
import type { CreateNoteUseCase } from '#src/use-cases/notes/CreateNoteUseCase.js';
import type { GetNotesUseCase } from '#src/use-cases/notes/GetNotesUseCase.js';
import type { UpdateNoteUseCase } from '#src/use-cases/notes/UpdateNoteUseCase.js';
import type { DeleteNoteUseCase } from '#src/use-cases/notes/DeleteNoteUseCase.js';
import type { RequestUploadUrlUseCase } from '#src/use-cases/documents/RequestUploadUrlUseCase.js';
import type { ConfirmDocumentUseCase } from '#src/use-cases/documents/ConfirmDocumentUseCase.js';
import type { GetDocumentsUseCase } from '#src/use-cases/documents/GetDocumentsUseCase.js';
import type { DeleteDocumentUseCase } from '#src/use-cases/documents/DeleteDocumentUseCase.js';
import type { CreateDocumentDraftUseCase } from '#src/use-cases/documents/CreateDocumentDraftUseCase.js';
import type { UpdateDocumentDraftContentUseCase } from '#src/use-cases/documents/UpdateDocumentDraftContentUseCase.js';
import type { RenameDocumentDraftUseCase } from '#src/use-cases/documents/RenameDocumentDraftUseCase.js';
import type { GenerateCoverLetterDraftUseCase } from '#src/use-cases/documents/GenerateCoverLetterDraftUseCase.js';
import type { GenerateResumeDraftUseCase } from '#src/use-cases/documents/GenerateResumeDraftUseCase.js';
import type { GenerateResumeUseCase } from '#src/use-cases/resume/GenerateResumeUseCase.js';
import type { GetDocumentDraftsUseCase } from '#src/use-cases/documents/GetDocumentDraftsUseCase.js';
import type { GetDocumentDraftUseCase } from '#src/use-cases/documents/GetDocumentDraftUseCase.js';
import type { DeleteDocumentDraftUseCase } from '#src/use-cases/documents/DeleteDocumentDraftUseCase.js';
import type { ExtractDocumentTextUseCase } from '#src/use-cases/documents/ExtractDocumentTextUseCase.js';
import type { ExportDocumentDraftToPdfUseCase } from '#src/use-cases/documents/ExportDocumentDraftToPdfUseCase.js';
import type { RequestEmailChangeUseCase } from '#src/use-cases/user/RequestEmailChangeUseCase.js';
import type { ConfirmEmailChangeUseCase } from '#src/use-cases/user/ConfirmEmailChangeUseCase.js';
import type { UpdatePasswordUseCase } from '#src/use-cases/user/UpdatePasswordUseCase.js';
import type { DeleteAccountUseCase } from '#src/use-cases/user/DeleteAccountUseCase.js';
import type { ExportUserDataUseCase } from '#src/use-cases/user/ExportUserDataUseCase.js';
import type { GenerateTotpSecretUseCase } from '#src/use-cases/user/GenerateTotpSecretUseCase.js';
import type { ConfirmTotpSetupUseCase } from '#src/use-cases/user/ConfirmTotpSetupUseCase.js';
import type { DisableTotpUseCase } from '#src/use-cases/user/DisableTotpUseCase.js';
import type { RegenerateTotpBackupCodesUseCase } from '#src/use-cases/user/RegenerateTotpBackupCodesUseCase.js';
import type { GetTotpStatusUseCase } from '#src/use-cases/user/GetTotpStatusUseCase.js';
import type { SaveLlmApiKeyUseCase } from '#src/use-cases/user/SaveLlmApiKeyUseCase.js';
import type { ListLlmApiKeysUseCase } from '#src/use-cases/user/ListLlmApiKeysUseCase.js';
import type { DeleteLlmApiKeyUseCase } from '#src/use-cases/user/DeleteLlmApiKeyUseCase.js';
import type { SetLlmApiKeyMonthlyLimitUseCase } from '#src/use-cases/user/SetLlmApiKeyMonthlyLimitUseCase.js';
import type { SetDefaultLlmProviderUseCase } from '#src/use-cases/user/SetDefaultLlmProviderUseCase.js';
import type { TestLlmApiKeyUseCase } from '#src/use-cases/user/TestLlmApiKeyUseCase.js';
import type { GetLlmUsageSummaryUseCase } from '#src/use-cases/user/GetLlmUsageSummaryUseCase.js';
import type { ImportUserDataUseCase } from '#src/use-cases/user/ImportUserDataUseCase.js';
import type { GetNotificationPreferencesUseCase } from '#src/use-cases/user/GetNotificationPreferencesUseCase.js';
import type { UpdateNotificationPreferencesUseCase } from '#src/use-cases/user/UpdateNotificationPreferencesUseCase.js';
import type { UpdateProfileUseCase } from '#src/use-cases/user/UpdateProfileUseCase.js';
import type { GetUserUseCase } from '#src/use-cases/user/GetUserUseCase.js';
import type { RequestAvatarUploadUrlUseCase } from '#src/use-cases/user/RequestAvatarUploadUrlUseCase.js';
import type { ConfirmAvatarUseCase } from '#src/use-cases/user/ConfirmAvatarUseCase.js';
import type { RemoveAvatarUseCase } from '#src/use-cases/user/RemoveAvatarUseCase.js';
import type { GetWeeklyApplicationGoalUseCase } from '#src/use-cases/user/GetWeeklyApplicationGoalUseCase.js';
import type { RequestAddBackupEmailUseCase } from '#src/use-cases/user/RequestAddBackupEmailUseCase.js';
import type { ConfirmBackupEmailUseCase } from '#src/use-cases/user/ConfirmBackupEmailUseCase.js';
import type { RemoveBackupEmailUseCase } from '#src/use-cases/user/RemoveBackupEmailUseCase.js';
import type { RequestBackupEmailRecoveryUseCase } from '#src/use-cases/auth/RequestBackupEmailRecoveryUseCase.js';
import type { CreateInterviewRoundUseCase } from '#src/use-cases/interviewRounds/CreateInterviewRoundUseCase.js';
import type { GetInterviewRoundsUseCase } from '#src/use-cases/interviewRounds/GetInterviewRoundsUseCase.js';
import type { UpdateInterviewRoundUseCase } from '#src/use-cases/interviewRounds/UpdateInterviewRoundUseCase.js';
import type { DeleteInterviewRoundUseCase } from '#src/use-cases/interviewRounds/DeleteInterviewRoundUseCase.js';
import type { GetActivityLogsUseCase } from '#src/use-cases/activityLogs/GetActivityLogsUseCase.js';
import type { GetLoginHistoryUseCase } from '#src/use-cases/loginEvents/GetLoginHistoryUseCase.js';
import type { GetSecurityActivityUseCase } from '#src/use-cases/securityEvents/GetSecurityActivityUseCase.js';
import type { GetChatHistoryUseCase } from '#src/use-cases/chat/GetChatHistoryUseCase.js';
import type { CreateConversationUseCase } from '#src/use-cases/conversations/CreateConversationUseCase.js';
import type { ListConversationsUseCase } from '#src/use-cases/conversations/ListConversationsUseCase.js';
import type { SearchConversationsUseCase } from '#src/use-cases/conversations/SearchConversationsUseCase.js';
import type { DeleteConversationUseCase } from '#src/use-cases/conversations/DeleteConversationUseCase.js';
import type { JwtTokenService } from '#src/infrastructure/auth/JwtTokenService.js';
import type { ApiTokenMapper } from '#src/interface-adapters/mappers/ApiTokenMapper.js';
import type { McpOAuthGrantMapper } from '#src/interface-adapters/mappers/McpOAuthGrantMapper.js';
import type { CreateApiTokenUseCase } from '#src/use-cases/apiTokens/CreateApiTokenUseCase.js';
import type { ListApiTokensUseCase } from '#src/use-cases/apiTokens/ListApiTokensUseCase.js';
import type { DeleteApiTokenUseCase } from '#src/use-cases/apiTokens/DeleteApiTokenUseCase.js';
import type { ValidateApiTokenUseCase } from '#src/use-cases/apiTokens/ValidateApiTokenUseCase.js';
import type { ShareLinkMapper } from '#src/interface-adapters/mappers/ShareLinkMapper.js';
import type { ShareLinkResolver } from '#src/interface-adapters/resolvers/ShareLinkResolver.js';
import type { CreateShareLinkUseCase } from '#src/use-cases/shareLinks/CreateShareLinkUseCase.js';
import type { ListShareLinksUseCase } from '#src/use-cases/shareLinks/ListShareLinksUseCase.js';
import type { DeleteShareLinkUseCase } from '#src/use-cases/shareLinks/DeleteShareLinkUseCase.js';
import type { GetSharedSummaryUseCase } from '#src/use-cases/shareLinks/GetSharedSummaryUseCase.js';
import type { NotificationMapper } from '#src/interface-adapters/mappers/NotificationMapper.js';
import type { CreateNotificationUseCase } from '#src/use-cases/notifications/CreateNotificationUseCase.js';
import type { GetNotificationsPageUseCase } from '#src/use-cases/notifications/GetNotificationsPageUseCase.js';
import type { MarkNotificationsReadUseCase } from '#src/use-cases/notifications/MarkNotificationsReadUseCase.js';
import type { RecordCookieConsentUseCase } from '#src/use-cases/cookieConsent/RecordCookieConsentUseCase.js';
import type { GetUnreadNotificationCountUseCase } from '#src/use-cases/notifications/GetUnreadNotificationCountUseCase.js';
import type { CreateContactUseCase } from '#src/use-cases/contacts/CreateContactUseCase.js';
import type { GetContactsUseCase } from '#src/use-cases/contacts/GetContactsUseCase.js';
import type { UpdateContactUseCase } from '#src/use-cases/contacts/UpdateContactUseCase.js';
import type { DeleteContactUseCase } from '#src/use-cases/contacts/DeleteContactUseCase.js';
import type { BrevoEmailService } from '#src/infrastructure/email/BrevoEmailService.js';
import type { ConsoleEmailService } from '#src/infrastructure/email/ConsoleEmailService.js';
import type { IDeviceLabeler } from '#src/use-cases/ports/IDeviceLabeler.js';
import type { IIpLocationResolver } from '#src/use-cases/ports/IIpLocationResolver.js';
import type { SendFollowUpRemindersUseCase } from '#src/use-cases/reminders/SendFollowUpRemindersUseCase.js';
import type { RegisterPushSubscriptionUseCase } from '#src/use-cases/push/RegisterPushSubscriptionUseCase.js';
import type { RegisterExpoPushTokenUseCase } from '#src/use-cases/push/RegisterExpoPushTokenUseCase.js';
import type { UnregisterPushSubscriptionUseCase } from '#src/use-cases/push/UnregisterPushSubscriptionUseCase.js';
import type { SendPushNotificationsUseCase } from '#src/use-cases/push/SendPushNotificationsUseCase.js';
import type { WebPushService } from '#src/infrastructure/push/WebPushService.js';
import type { ExpoPushService } from '#src/infrastructure/push/ExpoPushService.js';
import type { DrizzleTransactionManager } from '#src/infrastructure/db/DrizzleTransactionManager.js';
import type { LlmApiKeyMapper } from '#src/interface-adapters/mappers/LlmApiKeyMapper.js';
import type { LlmUsageSummaryMapper } from '#src/interface-adapters/mappers/LlmUsageSummaryMapper.js';
import type { ILlmApiKeyRepository } from '#src/use-cases/ports/ILlmApiKeyRepository.js';
import type { ILlmUsageEventRepository } from '#src/use-cases/ports/ILlmUsageEventRepository.js';
import type { ParseJobDescriptionUseCase } from '#src/use-cases/jobDescription/ParseJobDescriptionUseCase.js';
import type { IJobPostingSourceResolver } from '#src/use-cases/ports/IJobPostingSourceResolver.js';
import type { GenerateCoverLetterUseCase } from '#src/use-cases/coverLetter/GenerateCoverLetterUseCase.js';
import type { GenerateCompanyBriefingUseCase } from '#src/use-cases/companyBriefing/GenerateCompanyBriefingUseCase.js';
import type { GetCompanyBriefingUseCase } from '#src/use-cases/companyBriefing/GetCompanyBriefingUseCase.js';
import type { DrizzleCompanyBriefingRepository } from '#src/infrastructure/db/repositories/DrizzleCompanyBriefingRepository.js';
import type { CompanyBriefingMapper } from '#src/interface-adapters/mappers/CompanyBriefingMapper.js';
import type { CompanyBriefingResolver } from '#src/interface-adapters/resolvers/CompanyBriefingResolver.js';
import type { ComputeHealthScoreUseCase } from '#src/use-cases/application/ComputeHealthScoreUseCase.js';
import type { ComputeResumeMatchScoreUseCase } from '#src/use-cases/application/ComputeResumeMatchScoreUseCase.js';
import type { GetApplicationChannelAnalyticsUseCase } from '#src/use-cases/application/GetApplicationChannelAnalyticsUseCase.js';
import type { GetCalendarEventsUseCase } from '#src/use-cases/calendar/GetCalendarEventsUseCase.js';
import type { GetDocumentVersionOutcomesUseCase } from '#src/use-cases/documents/GetDocumentVersionOutcomesUseCase.js';
import type { GetInterviewRoundAnalyticsUseCase } from '#src/use-cases/interviewRounds/GetInterviewRoundAnalyticsUseCase.js';
import type { GetOfferAnalyticsUseCase } from '#src/use-cases/offers/GetOfferAnalyticsUseCase.js';
import type { GetResponseTimeAnalyticsUseCase } from '#src/use-cases/activityLogs/GetResponseTimeAnalyticsUseCase.js';
import type { SendWeeklyDigestUseCase } from '#src/use-cases/digest/SendWeeklyDigestUseCase.js';
import type { CreateSessionUseCase } from '#src/use-cases/sessions/CreateSessionUseCase.js';
import type { RotateRefreshTokenUseCase } from '#src/use-cases/sessions/RotateRefreshTokenUseCase.js';
import type { ListSessionsUseCase } from '#src/use-cases/sessions/ListSessionsUseCase.js';
import type { RevokeSessionUseCase } from '#src/use-cases/sessions/RevokeSessionUseCase.js';
import type { RevokeOtherSessionsUseCase } from '#src/use-cases/sessions/RevokeOtherSessionsUseCase.js';
import type { StreamChatWithAssistantUseCase } from '#src/use-cases/chat/StreamChatWithAssistantUseCase.js';
import type { LLMToolDefinition } from '#src/use-cases/ports/ILLMProvider.js';
import type { CreateWorkExperienceUseCase } from '#src/use-cases/workExperience/CreateWorkExperienceUseCase.js';
import type { UpdateWorkExperienceUseCase } from '#src/use-cases/workExperience/UpdateWorkExperienceUseCase.js';
import type { DeleteWorkExperienceUseCase } from '#src/use-cases/workExperience/DeleteWorkExperienceUseCase.js';
import type { CreateEducationUseCase } from '#src/use-cases/education/CreateEducationUseCase.js';
import type { UpdateEducationUseCase } from '#src/use-cases/education/UpdateEducationUseCase.js';
import type { DeleteEducationUseCase } from '#src/use-cases/education/DeleteEducationUseCase.js';
import type { CreateSkillUseCase } from '#src/use-cases/skill/CreateSkillUseCase.js';
import type { UpdateSkillUseCase } from '#src/use-cases/skill/UpdateSkillUseCase.js';
import type { DeleteSkillUseCase } from '#src/use-cases/skill/DeleteSkillUseCase.js';
import type { OfferMapper } from '#src/interface-adapters/mappers/OfferMapper.js';
import type { OfferResolver } from '#src/interface-adapters/resolvers/OfferResolver.js';
import type { CreateOfferUseCase } from '#src/use-cases/offers/CreateOfferUseCase.js';
import type { UpdateOfferUseCase } from '#src/use-cases/offers/UpdateOfferUseCase.js';
import type { DeleteOfferUseCase } from '#src/use-cases/offers/DeleteOfferUseCase.js';
import type { GetOffersUseCase } from '#src/use-cases/offers/GetOffersUseCase.js';
import type { CompareOffersUseCase } from '#src/use-cases/offers/CompareOffersUseCase.js';

import type { ILlmApiKeyCipher } from '#src/use-cases/ports/ILlmApiKeyCipher.js';
import type { IOutboundUrlPolicy } from '#src/use-cases/ports/IOutboundUrlPolicy.js';
import type { ILLMProviderFactory } from '#src/use-cases/ports/ILLMProviderFactory.js';
import type { IDocumentTextExtractor } from '#src/use-cases/ports/IDocumentTextExtractor.js';
import type { IPdfRenderer } from '#src/use-cases/ports/IPdfRenderer.js';
import type { ILogger } from '#src/use-cases/ports/ILogger.js';

export interface Cradle {
  db: typeof db;
  storageProvider: LocalStorageProvider | VercelBlobStorageProvider;
  generateId: () => string;
  now: () => Date;
  webAppOrigin: string;
  logger: ILogger;
  tokenService: JwtTokenService;
  cache: ICache;
  sessionBlocklist: ISessionBlocklist;
  passwordResetRateLimiter: IRateLimiter;

  // Raw repositories (used internally by the cached decorators)
  drizzleUserRepository: DrizzleUserRepository;
  drizzleApplicationRepository: DrizzleApplicationRepository;
  drizzleNoteRepository: DrizzleNoteRepository;
  drizzleDocumentRepository: DrizzleDocumentRepository;
  documentDraftRepository: DrizzleDocumentDraftRepository;
  drizzleSkillRepository: DrizzleSkillRepository;
  drizzleEducationRepository: DrizzleEducationRepository;
  drizzleWorkExperienceRepository: DrizzleWorkExperienceRepository;
  drizzleApiTokenRepository: DrizzleApiTokenRepository;
  drizzleMcpOAuthTokenRepository: DrizzleMcpOAuthTokenRepository;
  mcpOAuthTokenRepository: CachedMcpOAuthTokenRepository;
  mcpOAuthClientRepository: DrizzleMcpOAuthClientRepository;
  mcpOAuthAuthorizationCodeRepository: DrizzleMcpOAuthAuthorizationCodeRepository;
  mcpOAuthRefreshTokenRepository: DrizzleMcpOAuthRefreshTokenRepository;
  mcpOAuthGrantRepository: DrizzleMcpOAuthGrantRepository;
  drizzleContactRepository: DrizzleContactRepository;
  drizzleNotificationRepository: DrizzleNotificationRepository;

  // Cached repository decorators (what use-cases consume)
  applicationRepository: CachedApplicationRepository;
  noteRepository: CachedNoteRepository;
  documentRepository: CachedDocumentRepository;
  drizzleInterviewRoundRepository: DrizzleInterviewRoundRepository;
  interviewRoundRepository: CachedInterviewRoundRepository;
  userRepository: CachedUserRepository;
  skillRepository: CachedSkillRepository;
  educationRepository: CachedEducationRepository;
  workExperienceRepository: CachedWorkExperienceRepository;
  activityLogRepository: DrizzleActivityLogRepository;
  apiTokenRepository: CachedApiTokenRepository;
  shareLinkRepository: DrizzleShareLinkRepository;
  notificationRepository: CachedNotificationRepository;
  contactRepository: CachedContactRepository;
  passwordResetTokenRepository: DrizzlePasswordResetTokenRepository;
  loginEventRepository: DrizzleLoginEventRepository;
  securityEventRepository: DrizzleSecurityEventRepository;
  cookieConsentRepository: DrizzleCookieConsentRepository;
  messageRepository: DrizzleMessageRepository;
  conversationRepository: DrizzleConversationRepository;
  llmApiKeyRepository: ILlmApiKeyRepository;
  llmUsageEventRepository: ILlmUsageEventRepository;
  drizzleSessionRepository: DrizzleSessionRepository;
  sessionRepository: BlocklistingSessionRepository;
  offerRepository: DrizzleOfferRepository;
  emailVerificationTokenRepository: DrizzleEmailVerificationTokenRepository;
  totpBackupCodeRepository: DrizzleTotpBackupCodeRepository;
  totpRateLimiter: IRateLimiter;
  chatRateLimiter: IRateLimiter;
  generateCoverLetterRateLimiter: IRateLimiter;
  parseJobDescriptionRateLimiter: IRateLimiter;
  computeResumeMatchScoreRateLimiter: IRateLimiter;
  generateCompanyBriefingRateLimiter: IRateLimiter;
  testLlmApiKeyRateLimiter: IRateLimiter;
  updatePasswordRateLimiter: IRateLimiter;
  requestEmailChangeRateLimiter: IRateLimiter;
  backupEmailVerificationTokenRepository: DrizzleBackupEmailVerificationTokenRepository;
  requestAddBackupEmailRateLimiter: IRateLimiter;
  removeBackupEmailRateLimiter: IRateLimiter;
  backupEmailRecoveryRateLimiter: IRateLimiter;
  mcpOAuthRegistrationRateLimiter: IRateLimiter;
  mcpOAuthAuthorizationRateLimiter: IRateLimiter;
  mcpOAuthTokenRateLimiter: IRateLimiter;
  mcpOAuthRevocationRateLimiter: IRateLimiter;
  totpProvider: ITotpProvider;
  oauthAccountRepository: DrizzleOAuthAccountRepository;
  googleOAuthProvider: IOAuthProvider;
  gitHubOAuthProvider: IOAuthProvider;
  oauthProviderRegistry: OAuthProviderRegistry;
  oauthStateService: OAuthStateService;
  mobileOAuthHandoffService: MobileOAuthHandoffService;
  mcpOAuthConsentService: McpOAuthConsentService;

  applicationMapper: ApplicationMapper;
  apiTokenMapper: ApiTokenMapper;
  mcpOAuthGrantMapper: McpOAuthGrantMapper;
  shareLinkMapper: ShareLinkMapper;
  notificationMapper: NotificationMapper;
  noteMapper: NoteMapper;
  documentMapper: DocumentMapper;
  documentDraftMapper: DocumentDraftMapper;
  userMapper: UserMapper;
  interviewRoundMapper: InterviewRoundMapper;
  activityLogMapper: ActivityLogMapper;
  contactMapper: ContactMapper;
  loginEventMapper: LoginEventMapper;
  securityActivityMapper: SecurityActivityMapper;
  messageMapper: MessageMapper;
  conversationMapper: ConversationMapper;
  llmApiKeyMapper: LlmApiKeyMapper;
  llmUsageSummaryMapper: LlmUsageSummaryMapper;
  sessionMapper: SessionMapper;
  workExperienceMapper: WorkExperienceMapper;
  educationMapper: EducationMapper;
  skillMapper: SkillMapper;
  offerMapper: OfferMapper;
  oauthAccountMapper: OAuthAccountMapper;

  authResolver: AuthResolver;
  applicationResolver: ApplicationResolver;
  noteResolver: NoteResolver;
  documentResolver: DocumentResolver;
  documentDraftResolver: DocumentDraftResolver;
  userResolver: UserResolver;
  interviewRoundResolver: InterviewRoundResolver;
  activityLogResolver: ActivityLogResolver;
  contactResolver: ContactResolver;
  loginEventResolver: LoginEventResolver;
  securityActivityResolver: SecurityActivityResolver;
  apiTokenResolver: ApiTokenResolver;
  mcpOAuthGrantResolver: McpOAuthGrantResolver;
  shareLinkResolver: ShareLinkResolver;
  notificationResolver: NotificationResolver;
  cookieConsentResolver: CookieConsentResolver;
  sessionResolver: SessionResolver;
  workExperienceResolver: WorkExperienceResolver;
  educationResolver: EducationResolver;
  skillResolver: SkillResolver;
  offerResolver: OfferResolver;
  oauthResolver: OAuthResolver;
  mcpController: McpController;

  loginOrSignupWithOAuthUseCase: LoginOrSignupWithOAuthUseCase;
  linkOAuthAccountUseCase: LinkOAuthAccountUseCase;
  unlinkOAuthAccountUseCase: UnlinkOAuthAccountUseCase;
  listLinkedOAuthAccountsUseCase: ListLinkedOAuthAccountsUseCase;
  exchangeMobileOAuthCodeUseCase: ExchangeMobileOAuthCodeUseCase;

  authenticateRequestUseCase: AuthenticateRequestUseCase;
  authenticateMcpRequestUseCase: AuthenticateMcpRequestUseCase;
  validateMcpOAuthAccessTokenUseCase: ValidateMcpOAuthAccessTokenUseCase;
  createMcpOAuthAccessTokenUseCase: CreateMcpOAuthAccessTokenUseCase;
  registerMcpOAuthClientUseCase: RegisterMcpOAuthClientUseCase;
  createMcpOAuthAuthorizationCodeUseCase: CreateMcpOAuthAuthorizationCodeUseCase;
  exchangeMcpOAuthAuthorizationCodeUseCase: ExchangeMcpOAuthAuthorizationCodeUseCase;
  revokeMcpOAuthGrantUseCase: RevokeMcpOAuthGrantUseCase;
  createMcpOAuthRefreshTokenUseCase: CreateMcpOAuthRefreshTokenUseCase;
  rotateMcpOAuthRefreshTokenUseCase: RotateMcpOAuthRefreshTokenUseCase;
  listMcpOAuthGrantsUseCase: ListMcpOAuthGrantsUseCase;
  revokeMcpOAuthGrantForUserUseCase: RevokeMcpOAuthGrantForUserUseCase;
  registerUseCase: RegisterUseCase;
  loginUseCase: LoginUseCase;
  loginWithTotpUseCase: LoginWithTotpUseCase;
  reauthenticateUseCase: ReauthenticateUseCase;
  requestPasswordResetUseCase: RequestPasswordResetUseCase;
  resetPasswordUseCase: ResetPasswordUseCase;
  sendEmailVerificationUseCase: SendEmailVerificationUseCase;
  verifyEmailUseCase: VerifyEmailUseCase;
  createApplicationUseCase: CreateApplicationUseCase;
  getApplicationsUseCase: GetApplicationsUseCase;
  getApplicationsPageUseCase: GetApplicationsPageUseCase;
  getApplicationUseCase: GetApplicationUseCase;
  updateApplicationUseCase: UpdateApplicationUseCase;
  deleteApplicationUseCase: DeleteApplicationUseCase;
  restoreApplicationUseCase: RestoreApplicationUseCase;
  permanentlyDeleteApplicationUseCase: PermanentlyDeleteApplicationUseCase;
  listTrashedApplicationsUseCase: ListTrashedApplicationsUseCase;
  purgeExpiredApplicationsUseCase: PurgeExpiredApplicationsUseCase;
  bulkUpdateApplicationsUseCase: BulkUpdateApplicationsUseCase;
  bulkDeleteApplicationsUseCase: BulkDeleteApplicationsUseCase;
  bulkRestoreApplicationsUseCase: BulkRestoreApplicationsUseCase;
  emptyTrashUseCase: EmptyTrashUseCase;
  getApplicationSectionCountsUseCase: GetApplicationSectionCountsUseCase;
  bulkAddTagToApplicationsUseCase: BulkAddTagToApplicationsUseCase;
  moveApplicationOnBoardUseCase: MoveApplicationOnBoardUseCase;
  createNoteUseCase: CreateNoteUseCase;
  getNotesUseCase: GetNotesUseCase;
  updateNoteUseCase: UpdateNoteUseCase;
  deleteNoteUseCase: DeleteNoteUseCase;
  requestUploadUrlUseCase: RequestUploadUrlUseCase;
  confirmDocumentUseCase: ConfirmDocumentUseCase;
  getDocumentsUseCase: GetDocumentsUseCase;
  deleteDocumentUseCase: DeleteDocumentUseCase;
  createDocumentDraftUseCase: CreateDocumentDraftUseCase;
  updateDocumentDraftContentUseCase: UpdateDocumentDraftContentUseCase;
  renameDocumentDraftUseCase: RenameDocumentDraftUseCase;
  generateCoverLetterDraftUseCase: GenerateCoverLetterDraftUseCase;
  generateResumeDraftUseCase: GenerateResumeDraftUseCase;
  generateResumeUseCase: GenerateResumeUseCase;
  generateResumeRateLimiter: IRateLimiter;
  getDocumentDraftsUseCase: GetDocumentDraftsUseCase;
  getDocumentDraftUseCase: GetDocumentDraftUseCase;
  deleteDocumentDraftUseCase: DeleteDocumentDraftUseCase;
  extractDocumentTextUseCase: ExtractDocumentTextUseCase;
  exportDocumentDraftToPdfUseCase: ExportDocumentDraftToPdfUseCase;
  requestEmailChangeUseCase: RequestEmailChangeUseCase;
  confirmEmailChangeUseCase: ConfirmEmailChangeUseCase;
  updatePasswordUseCase: UpdatePasswordUseCase;
  deleteAccountUseCase: DeleteAccountUseCase;
  exportUserDataUseCase: ExportUserDataUseCase;
  generateTotpSecretUseCase: GenerateTotpSecretUseCase;
  confirmTotpSetupUseCase: ConfirmTotpSetupUseCase;
  disableTotpUseCase: DisableTotpUseCase;
  regenerateTotpBackupCodesUseCase: RegenerateTotpBackupCodesUseCase;
  getTotpStatusUseCase: GetTotpStatusUseCase;
  saveLlmApiKeyUseCase: SaveLlmApiKeyUseCase;
  listLlmApiKeysUseCase: ListLlmApiKeysUseCase;
  deleteLlmApiKeyUseCase: DeleteLlmApiKeyUseCase;
  setDefaultLlmProviderUseCase: SetDefaultLlmProviderUseCase;
  setLlmApiKeyMonthlyLimitUseCase: SetLlmApiKeyMonthlyLimitUseCase;
  testLlmApiKeyUseCase: TestLlmApiKeyUseCase;
  getLlmUsageSummaryUseCase: GetLlmUsageSummaryUseCase;
  importUserDataUseCase: ImportUserDataUseCase;
  getNotificationPreferencesUseCase: GetNotificationPreferencesUseCase;
  updateNotificationPreferencesUseCase: UpdateNotificationPreferencesUseCase;
  updateProfileUseCase: UpdateProfileUseCase;
  getUserUseCase: GetUserUseCase;
  requestAvatarUploadUrlUseCase: RequestAvatarUploadUrlUseCase;
  confirmAvatarUseCase: ConfirmAvatarUseCase;
  removeAvatarUseCase: RemoveAvatarUseCase;
  getWeeklyApplicationGoalUseCase: GetWeeklyApplicationGoalUseCase;
  requestAddBackupEmailUseCase: RequestAddBackupEmailUseCase;
  confirmBackupEmailUseCase: ConfirmBackupEmailUseCase;
  removeBackupEmailUseCase: RemoveBackupEmailUseCase;
  requestBackupEmailRecoveryUseCase: RequestBackupEmailRecoveryUseCase;
  createInterviewRoundUseCase: CreateInterviewRoundUseCase;
  getInterviewRoundsUseCase: GetInterviewRoundsUseCase;
  updateInterviewRoundUseCase: UpdateInterviewRoundUseCase;
  deleteInterviewRoundUseCase: DeleteInterviewRoundUseCase;
  getActivityLogsUseCase: GetActivityLogsUseCase;
  getLoginHistoryUseCase: GetLoginHistoryUseCase;
  getSecurityActivityUseCase: GetSecurityActivityUseCase;
  getChatHistoryUseCase: GetChatHistoryUseCase;
  createConversationUseCase: CreateConversationUseCase;
  listConversationsUseCase: ListConversationsUseCase;
  searchConversationsUseCase: SearchConversationsUseCase;
  deleteConversationUseCase: DeleteConversationUseCase;
  createApiTokenUseCase: CreateApiTokenUseCase;
  listApiTokensUseCase: ListApiTokensUseCase;
  deleteApiTokenUseCase: DeleteApiTokenUseCase;
  validateApiTokenUseCase: ValidateApiTokenUseCase;
  createShareLinkUseCase: CreateShareLinkUseCase;
  listShareLinksUseCase: ListShareLinksUseCase;
  deleteShareLinkUseCase: DeleteShareLinkUseCase;
  getSharedSummaryUseCase: GetSharedSummaryUseCase;
  createNotificationUseCase: CreateNotificationUseCase;
  getNotificationsPageUseCase: GetNotificationsPageUseCase;
  markNotificationsReadUseCase: MarkNotificationsReadUseCase;
  recordCookieConsentUseCase: RecordCookieConsentUseCase;
  getUnreadNotificationCountUseCase: GetUnreadNotificationCountUseCase;
  createContactUseCase: CreateContactUseCase;
  getContactsUseCase: GetContactsUseCase;
  updateContactUseCase: UpdateContactUseCase;
  deleteContactUseCase: DeleteContactUseCase;
  emailService: BrevoEmailService | ConsoleEmailService;
  deviceLabeler: IDeviceLabeler;
  ipLocationResolver: IIpLocationResolver;
  webPushService: WebPushService;
  expoPushService: ExpoPushService;
  pushSubscriptionRepository: DrizzlePushSubscriptionRepository;
  registerPushSubscriptionUseCase: RegisterPushSubscriptionUseCase;
  registerExpoPushTokenUseCase: RegisterExpoPushTokenUseCase;
  unregisterPushSubscriptionUseCase: UnregisterPushSubscriptionUseCase;
  sendPushNotificationsUseCase: SendPushNotificationsUseCase;
  sendFollowUpRemindersUseCase: SendFollowUpRemindersUseCase;
  transactionManager: DrizzleTransactionManager;
  outboundUrlPolicy: IOutboundUrlPolicy;
  llmApiKeyCipher: ILlmApiKeyCipher;
  userLlmProviderFactory: ILLMProviderFactory;
  llmProviderFactory: ILLMProviderFactory;
  documentTextExtractor: IDocumentTextExtractor;
  pdfRenderer: IPdfRenderer;
  jobPostingSourceResolver: IJobPostingSourceResolver;
  parseJobDescriptionUseCase: ParseJobDescriptionUseCase;
  generateCoverLetterUseCase: GenerateCoverLetterUseCase;
  generateCompanyBriefingUseCase: GenerateCompanyBriefingUseCase;
  getCompanyBriefingUseCase: GetCompanyBriefingUseCase;
  companyBriefingRepository: DrizzleCompanyBriefingRepository;
  companyBriefingMapper: CompanyBriefingMapper;
  companyBriefingResolver: CompanyBriefingResolver;
  computeHealthScoreUseCase: ComputeHealthScoreUseCase;
  chatTools: LLMToolDefinition[];
  streamChatWithAssistantUseCase: StreamChatWithAssistantUseCase;
  computeResumeMatchScoreUseCase: ComputeResumeMatchScoreUseCase;
  getApplicationChannelAnalyticsUseCase: GetApplicationChannelAnalyticsUseCase;
  getCalendarEventsUseCase: GetCalendarEventsUseCase;
  getDocumentVersionOutcomesUseCase: GetDocumentVersionOutcomesUseCase;
  getInterviewRoundAnalyticsUseCase: GetInterviewRoundAnalyticsUseCase;
  getOfferAnalyticsUseCase: GetOfferAnalyticsUseCase;
  getResponseTimeAnalyticsUseCase: GetResponseTimeAnalyticsUseCase;
  sendWeeklyDigestUseCase: SendWeeklyDigestUseCase;
  createSessionUseCase: CreateSessionUseCase;
  rotateRefreshTokenUseCase: RotateRefreshTokenUseCase;
  listSessionsUseCase: ListSessionsUseCase;
  revokeSessionUseCase: RevokeSessionUseCase;
  revokeOtherSessionsUseCase: RevokeOtherSessionsUseCase;
  createWorkExperienceUseCase: CreateWorkExperienceUseCase;
  updateWorkExperienceUseCase: UpdateWorkExperienceUseCase;
  deleteWorkExperienceUseCase: DeleteWorkExperienceUseCase;
  createEducationUseCase: CreateEducationUseCase;
  updateEducationUseCase: UpdateEducationUseCase;
  deleteEducationUseCase: DeleteEducationUseCase;
  createSkillUseCase: CreateSkillUseCase;
  updateSkillUseCase: UpdateSkillUseCase;
  deleteSkillUseCase: DeleteSkillUseCase;
  createOfferUseCase: CreateOfferUseCase;
  updateOfferUseCase: UpdateOfferUseCase;
  deleteOfferUseCase: DeleteOfferUseCase;
  getOffersUseCase: GetOffersUseCase;
  compareOffersUseCase: CompareOffersUseCase;
}
