//! In-memory doubles for the ports, one module per domain, for use-case
//! tests. Cross-cutting doubles (tokens, blocklist, ids) are in
//! `infrastructure`.

mod activity_logs;
mod api_tokens;
mod applications;
mod auth_providers;
mod backup_email_verification_tokens;
mod devices;
mod email_verification_tokens;
mod emails;
mod infrastructure;
mod llm;
mod llm_api_keys;
mod llm_usage_events;
mod logging;
mod login_events;
mod mcp_oauth;
pub mod metrics;
mod net;
mod notes;
mod oauth_accounts;
mod password_reset_tokens;
mod security_events;
mod sessions;
mod share_links;
mod storage;
mod totp_backup_codes;
mod transactions;
mod users;

pub use activity_logs::FakeActivityLogRepository;
pub use api_tokens::FakeApiTokenRepository;
pub use applications::{application_owned_by, FakeApplicationRepository};
pub use auth_providers::*;
pub use backup_email_verification_tokens::FakeBackupEmailVerificationTokenRepository;
pub use devices::{FakeDeviceLabeler, FakeIpLocationResolver};
pub use email_verification_tokens::FakeEmailVerificationTokenRepository;
pub use emails::{FakeEmailService, SentEmail};
pub use infrastructure::{sequential_ids, FakeSessionBlocklist, FakeTokenService};
pub use llm::*;
pub use llm_api_keys::FakeLlmApiKeyRepository;
pub use llm_usage_events::FakeLlmUsageEventRepository;
pub use logging::{FakeLogger, LogLevel, LoggedLine};
pub use login_events::FakeLoginEventRepository;
pub use mcp_oauth::*;
pub use metrics::FakeMetrics;
pub use net::FakeOutboundUrlPolicy;
pub use notes::FakeNoteRepository;
pub use oauth_accounts::FakeOAuthAccountRepository;
pub use password_reset_tokens::FakePasswordResetTokenRepository;
pub use security_events::FakeSecurityEventRepository;
pub use sessions::{session_for, FakeSessionRepository};
pub use share_links::FakeShareLinkRepository;
pub use storage::{FakeStorageProvider, StoredObject};
pub use totp_backup_codes::FakeTotpBackupCodeRepository;
pub use transactions::FakeTransactionManager;
pub use users::{user_with_email, FakeUserRepository};
mod company_briefings;
mod contacts;
mod conversations;
mod cookie_consents;
mod document_drafts;
mod documents;
mod educations;
mod interview_rounds;
mod messages;
mod notifications;
mod offers;
mod push_subscriptions;
mod skills;
mod work_experiences;

pub use company_briefings::FakeCompanyBriefingRepository;
pub use contacts::FakeContactRepository;
pub use conversations::FakeConversationRepository;
pub use cookie_consents::FakeCookieConsentRepository;
pub use document_drafts::FakeDocumentDraftRepository;
pub use documents::FakeDocumentRepository;
pub use educations::FakeEducationRepository;
pub use interview_rounds::FakeInterviewRoundRepository;
pub use messages::FakeMessageRepository;
pub use notifications::FakeNotificationRepository;
pub use offers::FakeOfferRepository;
pub use push_subscriptions::FakePushSubscriptionRepository;
pub use skills::FakeSkillRepository;
pub use work_experiences::FakeWorkExperienceRepository;
